#!/usr/bin/env python3
"""Bundle the modular cetuslib package into a single executable file.

Usage:
    python3 scripts/bundle-monolith.py [output_path]

Default output: dist/cetus
"""

import os
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = PROJECT_ROOT / 'cetuslib'
DEFAULT_OUTPUT = PROJECT_ROOT / 'dist' / 'cetus'

# Order matters: modules with no internal dependencies first.
MODULE_ORDER = [
    'constants.py',
    'config.py',
    'utils.py',
    'vendors.py',
    'terminal.py',
    'workers.py',
    'automation_worker.py',
    'automation.py',
    'network.py',
    'ui/__init__.py',
    'ui/dialogs.py',
    'ui/profiles.py',
    'ui/widgets.py',
    'legacy.py',
    'main.py',
]


def strip_cetuslib_imports(text: str) -> str:
    """Remove imports of other cetuslib modules; symbols will be in global scope."""
    # Remove parenthesized multi-line imports: from cetuslib.<module> import ( ... )
    text = re.sub(r"^from cetuslib(?:\.\w+)+ import \(.*?\)\n", "", text, flags=re.DOTALL | re.MULTILINE)
    # Remove single-line 'from cetuslib.<module> import <names>'
    text = re.sub(r"^from cetuslib(?:\.\w+)+ import .*$\n?", "", text, flags=re.MULTILINE)
    # Remove 'import cetuslib.<module>' lines
    text = re.sub(r"^import cetuslib(?:\.\w+)+$\n?", "", text, flags=re.MULTILINE)
    return text


def strip_module_metadata(text: str) -> str:
    """Remove shebangs and __all__ declarations; keep everything else."""
    lines = text.splitlines(keepends=True)
    result = []
    for line in lines:
        if line.startswith('#!'):
            continue
        result.append(line)
    text = ''.join(result)
    # Remove multi-line __all__ = [ ... ] assignments.
    text = re.sub(r"__all__\s*=\s*\[.*?\]\n", "", text, flags=re.DOTALL)
    return text


def bundle(output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    parts = []
    parts.append('#!/usr/bin/env python3\n')
    parts.append('"""Cetus — bundled monolithic executable.\n')
    parts.append('This file is generated by scripts/bundle-monolith.py.\n')
    parts.append('Do not edit directly; modify cetuslib/ instead.\n"""\n\n')

    for module_name in MODULE_ORDER:
        module_path = PACKAGE_DIR / module_name
        if not module_path.exists():
            continue
        text = module_path.read_text(encoding='utf-8')
        text = strip_module_metadata(text)
        text = strip_cetuslib_imports(text)
        parts.append(f'\n# ----- {module_name} -----\n')
        parts.append(text)
        if not text.endswith('\n'):
            parts.append('\n')

    # Ensure the bundled file calls main() when executed directly.
    parts.append('\n\nif __name__ == \'__main__\':\n')
    parts.append('    main()\n')

    output_path.write_text(''.join(parts), encoding='utf-8')
    output_path.chmod(0o755)
    print(f'Bundled {len(MODULE_ORDER)} modules into {output_path}')


if __name__ == '__main__':
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    bundle(output)
